title:              Jake Park
email:              jaekpark@student.42seoul.kr
description:        비전공자의 개발도전기
author:             jaekpark
baseurl:            ""
url:                "https://jaekpark.github.io"

# Social Profiles
twitter_username:   
github_username:    jaekpark
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
